'use strict';

const vscode = require('vscode');
const path   = require('path');
const fs     = require('fs');
const os     = require('os');
const cp     = require('child_process');

// ─── Core helpers (state, config, logging) ────────────────────────────────────
const H = require('./helpers');
const {
        IS_WIN, IS_LINUX,
        log, cfg, setCfg, q, getValidIdfPath,
        warnNoProject, getUserShell,
        setBusy, clearBusy, checkBusy,
        findXtensaGcc, getTerm, buildCmd, buildIdfEnvPrefix,
        watchCommandDone, buildMarkerCmd, ensureVersionTxt,
        getActiveRoot, setActiveRoot, getGlobalCtx, setGlobalCtx,
        getOutputChannel, setOutputChannel,
        setPortCache,
        setPythonCmdCache,
        setToolsVerified,
        setSdkVersionCache,
        setMonitorRunning,
        setProvider, setPartitionPanel,
        setSdkconfigCache,
        getPartitionPanel, getProvider, getPushSdkconfigUpdate,
        getGlobalBusyName, getMonitorRunning,
        getPartitionCsvFilename, getSdkconfigValue,
        getIdfPathOverride, setIdfPathOverride,
        getTerms, setTerms,
        FLASH_SIZE_MAP,
} = H;

// ─── Feature modules ──────────────────────────────────────────────────────────
const Python         = require('./python');
const Ports          = require('./ports');
const StatusBar      = require('./statusBar');
const IdfRunner      = require('./idfRunner');
const Flash          = require('./flash');
const Components     = require('./components');
const TreeProvider   = require('./treeProvider');
const PartitionEditor = require('./partitionEditor');
const OtaFlash       = require('./otaFlash');
const CmakeEditor    = require('./cmakeEditor');
const NewProjectEditor = require('./newProjectEditor');
const SettingsEditor = require('./settingsEditor');

// ╔══════════════════════════════════════════════════════════════════╗
// ║  PROJECT SETUP: IntelliSense, Tasks, Auto-generate                 ║
// ╚══════════════════════════════════════════════════════════════════╝
async function autoGenerateDevFiles() {
    if (!cfg('autoGenerateOnOpen')) return;
    if (checkBusy()) return;

    const root     = getActiveRoot();
    const idfPath  = getValidIdfPath();
    if (!root || !idfPath) return;

    const vscodeDir      = path.join(root, '.vscode');
    const intelliSense   = path.join(vscodeDir, 'c_cpp_properties.json');
    const tasksFile      = path.join(vscodeDir, 'tasks.json');

    const needIntelliSense = !fs.existsSync(intelliSense);
    const needTasks        = !fs.existsSync(tasksFile);

    if (!needIntelliSense && !needTasks) return;

    const pythonCmd = await Python.getPythonCmd();
    if (!pythonCmd) return;

    try { fs.mkdirSync(vscodeDir, { recursive: true }); } catch {}

    const generated = [];

    if (needIntelliSense) {
        try {
            const compilerPath        = findXtensaGcc();
            const compileCommandsPath = '${workspaceFolder}/build/compile_commands.json';
            const compileCommandsReal = path.join(root, 'build', 'compile_commands.json');
            const config = {
                configurations:[{
                    name: 'ESP8266',
                    includePath:['${workspaceFolder}/**', `${idfPath}/components/**`],
                    defines:['ESP_PLATFORM', '__xtensa__', '__XTENSA__'],
                    ...(compilerPath ? { compilerPath } : {}),
                    compileCommands: compileCommandsPath,
                    cStandard: 'gnu11',
                    cppStandard: 'gnu++14',
                    browse: {
                        path:['${workspaceFolder}', idfPath],
                        limitSymbolsToIncludedHeaders: true
                    }
                }],
                version: 4
            };
            fs.writeFileSync(intelliSense, JSON.stringify(config, null, 4));
            generated.push('c_cpp_properties.json');
            log('Auto-generated c_cpp_properties.json');
            if (!fs.existsSync(compileCommandsReal)) {
                vscode.window.showInformationMessage(
                    'ESP: c_cpp_properties.json generated. Run Build first for accurate IntelliSense (compile_commands.json not found yet).',
                    'Build Now'
                ).then(ans => { if (ans === 'Build Now') vscode.commands.executeCommand('esp.build'); });
            }
        } catch (e) {
            log(`Auto-generate IntelliSense failed: ${e.message}`);
        }
    }

    if (needTasks) {
        try {
            const envPrefix  = buildIdfEnvPrefix(idfPath, pythonCmd);
            const shellOpts  = IS_WIN
                ? { executable: 'powershell.exe', args:['-ExecutionPolicy', 'Bypass', '-NoLogo', '-Command'] }
                : { executable: getUserShell(), args:['-c'] };
            const makeShellCmd = (idfArgs) => IS_WIN
                ? `${envPrefix}; idf.py ${idfArgs.join(' ')}`
                : `${envPrefix} && idf.py ${idfArgs.join(' ')}`;
            const makeTask = (label, idfArgs, isDefault = false) => ({
                label, type: 'shell',
                command: makeShellCmd(idfArgs),
                options: { cwd: '${workspaceFolder}', ...(IS_WIN ? { shell: shellOpts } : {}) },
                ...(isDefault ? { group: { kind: 'build', isDefault: true } } : {}),
                presentation: { reveal: 'always', focus: true, panel: 'shared', clear: true },
                problemMatcher: '$esp-idf-gcc',
            });
            const tasksJson = {
                version: '2.0.0',
                tasks:[
                    makeTask('ESP: Build',            ['build'], true),
                    makeTask('ESP: Build App',        ['app']),
                    makeTask('ESP: Build Bootloader', ['bootloader']),
                    makeTask('ESP: Clean',            ['clean']),
                    makeTask('ESP: Full Clean',       ['fullclean']),
                    makeTask('ESP: Size',             ['size']),
                ]
            };
            fs.writeFileSync(tasksFile, JSON.stringify(tasksJson, null, 4));
            generated.push('tasks.json');
            log('Auto-generated tasks.json');
        } catch (e) {
            log(`Auto-generate tasks.json failed: ${e.message}`);
        }
    }

    if (generated.length) {
        vscode.window.showInformationMessage(
            `ESP-IDF: Auto-generated ${generated.join(' and ')} for this project.`
        );
    }
}

function checkDialoutGroup() {
    if (!IS_LINUX) return;
    cp.exec('id -nG', { encoding: 'utf8' }, (err, stdout) => {
        if (err) return;
        const groups = stdout.trim().split(' ');
        if (!groups.includes('dialout') && !groups.includes('uucp')) {
            vscode.window.showWarningMessage(
                'ESP: User not in dialout group. Serial port access errors possible.',
                'How to fix'
            ).then(choice => {
                if (choice === 'How to fix') {
                    vscode.window.showInformationMessage(
                        `Run: sudo usermod -aG dialout ${os.userInfo().username} — then restart your session.`
                    );
                }
            });
        }
    });
}

async function cmdGenerateIntelliSense() {
    if (!await Python.requireReady()) return;
    const root = getActiveRoot();
    if (!root) { warnNoProject(); return; }
    const idfPath = getValidIdfPath();
    if (!idfPath) { vscode.window.showErrorMessage('ESP: IDF path not set!'); return; }

    const vscodeDir  = path.join(root, '.vscode');
    const outFile    = path.join(vscodeDir, 'c_cpp_properties.json');
    const compilerPath = findXtensaGcc();

    const compileCommandsPath = '${workspaceFolder}/build/compile_commands.json';

    const config = {
        configurations:[{
            name: 'ESP8266',
            includePath:[
                '${workspaceFolder}/**',
                `${idfPath}/components/**`,
            ],
            defines:[
                'ESP_PLATFORM',
                '__xtensa__',
                '__XTENSA__',
            ],
            ...(compilerPath ? { compilerPath } : {}),
            compileCommands: compileCommandsPath,
            cStandard: 'gnu11',
            cppStandard: 'gnu++14',
            browse: {
                path: ['${workspaceFolder}', idfPath],
                limitSymbolsToIncludedHeaders: true
            }
        }],
        version: 4
    };

    if (fs.existsSync(outFile)) {
        const choice = await vscode.window.showWarningMessage(
            '.vscode/c_cpp_properties.json already exists. Overwrite?',
            'Overwrite', 'Cancel'
        );
        if (choice !== 'Overwrite') return;
    }

    try {
        fs.mkdirSync(vscodeDir, { recursive: true });
        fs.writeFileSync(outFile, JSON.stringify(config, null, 4));

        const compileCommandsReal = path.join(root, 'build', 'compile_commands.json');
        const noCompileCommands   = !fs.existsSync(compileCommandsReal);

        const hint = noCompileCommands
            ? 'Run Build first for accurate IntelliSense (compile_commands.json not found yet)'
            : compilerPath
                ? `Compiler: ${path.basename(compilerPath)}`
                : 'Compiler not found — run Build for full IntelliSense';

        const action = await vscode.window.showInformationMessage(
            `✅ c_cpp_properties.json generated. ${hint}`,
            noCompileCommands ? 'Build Now' : 'Open File'
        );
        if (action === 'Build Now') vscode.commands.executeCommand('esp.build');
        if (action === 'Open File') vscode.window.showTextDocument(vscode.Uri.file(outFile));
        log(`Generated c_cpp_properties.json (compiler: ${compilerPath || 'not found'})`);
    } catch (e) {
        vscode.window.showErrorMessage(`Failed to write c_cpp_properties.json: ${e.message}`);
    }
}

async function cmdGenerateTasks() {
    if (!await Python.requireReady()) return;
    const root = getActiveRoot();
    if (!root) { warnNoProject(); return; }
    const idfPath = getValidIdfPath();
    if (!idfPath) { vscode.window.showErrorMessage('ESP: IDF path not set!'); return; }
    const pythonCmd = await Python.getPythonCmd();
    if (!pythonCmd) return;

    const envPrefix = buildIdfEnvPrefix(idfPath, pythonCmd);

    const makeShellCmd = (idfArgs) => IS_WIN
        ? `${envPrefix}; idf.py ${idfArgs.join(' ')}`
        : `${envPrefix} && idf.py ${idfArgs.join(' ')}`;

    const shellOpts = IS_WIN
        ? { executable: 'powershell.exe', args:['-ExecutionPolicy', 'Bypass', '-NoLogo', '-Command'] }
        : { executable: getUserShell(), args: ['-c'] };

    const makeTask = (label, idfArgs, isDefaultBuild = false) => ({
        label,
        type: 'shell',
        command: makeShellCmd(idfArgs),
        options: {
            cwd: '${workspaceFolder}',
            ...(IS_WIN ? { shell: shellOpts } : {})
        },
        ...(isDefaultBuild ? { group: { kind: 'build', isDefault: true } } : {}),
        presentation: { reveal: 'always', focus: true, panel: 'shared', clear: true },
        problemMatcher: '$esp-idf-gcc',
    });

    const tasksJson = {
        version: '2.0.0',
        tasks:[
            makeTask('ESP: Build',            ['build'],           true),
            makeTask('ESP: Build App',        ['app']),
            makeTask('ESP: Build Bootloader',['bootloader']),
            makeTask('ESP: Clean',            ['clean']),
            makeTask('ESP: Full Clean',       ['fullclean']),
            makeTask('ESP: Size',             ['size']),
        ]
    };

    const vscodeDir = path.join(root, '.vscode');
    const outFile   = path.join(vscodeDir, 'tasks.json');

    if (fs.existsSync(outFile)) {
        const choice = await vscode.window.showWarningMessage(
            '.vscode/tasks.json already exists. Overwrite?',
            'Overwrite', 'Cancel'
        );
        if (choice !== 'Overwrite') return;
    }

    try {
        fs.mkdirSync(vscodeDir, { recursive: true });
        fs.writeFileSync(outFile, JSON.stringify(tasksJson, null, 4));

        const action = await vscode.window.showInformationMessage(
            '✅ tasks.json generated. Use Ctrl+Shift+B to build.',
            'Open File'
        );
        if (action === 'Open File') {
            vscode.window.showTextDocument(vscode.Uri.file(outFile));
        }
        log('Generated .vscode/tasks.json');
    } catch (e) {
        vscode.window.showErrorMessage(`Failed to write tasks.json: ${e.message}`);
    }
}

// ╔══════════════════════════════════════════════════════════════════╗
// ║  PROJECT CREATION WIZARD                                           ║
// ╚══════════════════════════════════════════════════════════════════╝
async function cmdEditProject() {
    if (checkBusy()) return;
    const root = getActiveRoot();
    if (!root) { warnNoProject(); return; }

    const mainCmake = path.join(root, 'main', 'CMakeLists.txt');
    const rootCmake = path.join(root, 'CMakeLists.txt');

    const items = [];
    if (fs.existsSync(mainCmake)) {
        items.push({ label: '$(file-code) Edit main/CMakeLists.txt', description: 'Component editor (SRCS, REQUIRES, ...)', value: 'main' });
    }
    if (fs.existsSync(rootCmake)) {
        items.push({ label: '$(root-folder-opened) Edit Root CMakeLists.txt', description: 'Root editor (project, EXCLUDE_COMPONENTS, ...)', value: 'root' });
    }

    if (items.length === 0) {
        vscode.window.showErrorMessage('ESP: No CMakeLists.txt found.');
        return;
    }

    if (items.length === 1) {
        // Only one option — open directly
        if (items[0].value === 'root') {
            CmakeEditor.cmdCmakeEditorRoot();
        } else {
            CmakeEditor.cmdCmakeEditorMain();
        }
        return;
    }

    const picked = await vscode.window.showQuickPick(items, {
        title: 'ESP CMake Editor — Which file to edit?',
        placeHolder: 'Select CMakeLists.txt to edit visually',
    });
    if (!picked) return;

    if (picked.value === 'root') {
        CmakeEditor.cmdCmakeEditorRoot();
    } else {
        CmakeEditor.cmdCmakeEditorMain();
    }
}

async function cmdCreateProject() {
    if (checkBusy()) return;
    NewProjectEditor.cmdNewProjectEditor();
}

// ╔══════════════════════════════════════════════════════════════════╗
// ║  SETTINGS COMMANDS                                                  ║
// ╚══════════════════════════════════════════════════════════════════╝
async function cmdSelectProject() {
    if (checkBusy()) return;
    if (getPartitionPanel()) {
        vscode.window.showWarningMessage('ESP: Close the Partition Editor before switching projects.');
        return;
    }
    const folders = vscode.workspace.workspaceFolders;
    if (!folders?.length) {
        vscode.commands.executeCommand('workbench.action.files.openFolder');
        return;
    }
    const items = folders.map(f => ({
        label: path.basename(f.uri.fsPath),
        description: f.uri.fsPath,
        detail: f.uri.fsPath === getActiveRoot() ? '$(check) active' : '',
        fsPath: f.uri.fsPath,
    }));
    const picked = await vscode.window.showQuickPick(items, {
        title: 'ESP-IDF Tools › Select project', placeHolder: 'Select workspace folder'
    });
    if (!picked) return;
    // Close all editor webviews before switching project
    CmakeEditor.closeAllCmakePanels();
    NewProjectEditor.closeNewProjectPanel();
    Components.closeAddComponentPanel();
    Components.closeEditComponentPanel();
    SettingsEditor.closeSettingsPanel();
    if (getPartitionPanel()) { getPartitionPanel().dispose(); setPartitionPanel(null); }
    setActiveRoot(picked.fsPath);
    setPortCache({ data: [], timestamp: 0 });
    if (getGlobalCtx()) getGlobalCtx().workspaceState.update('espActiveRoot', picked.fsPath);
    vscode.window.showInformationMessage(`ESP: Project → ${path.basename(picked.fsPath)}`);
}

// ╔══════════════════════════════════════════════════════════════════╗
// ║  SETTINGS COMMANDS (now handled by SettingsEditor webview)          ║
// ╚══════════════════════════════════════════════════════════════════╝
// cmdConfigureBuild, cmdConfigureBuildSimple, cmdConfigureFlash,
// cmdConfigureFlashApp, cmdConfigureFlashFs — all moved to settingsEditor.js

async function cmdSelectFlashBaud() {
    if (checkBusy()) return;
    const picked = await vscode.window.showQuickPick(['9600','19200','38400','57600','74880','115200','230400','460800','921600','1500000','2000000'].map(b => ({ label: b })),
        { title: 'ESP-IDF Tools › Flash Baud Rate' }
    );
    if (picked) await setCfg('flashBaud', parseInt(picked.label, 10));
}

async function cmdSelectFlashMode() {
    if (checkBusy()) return;
    const picked = await vscode.window.showQuickPick(['dio','dout','qio','qout'].map(m => ({ label: m })),
        { title: 'ESP-IDF Tools › Flash Mode' }
    );
    if (picked) await setCfg('flashMode', picked.label);
}

async function cmdSelectFlashFreq() {
    if (checkBusy()) return;
    const picked = await vscode.window.showQuickPick(['40m','80m','20m','26m'].map(f => ({ label: f })),
        { title: 'ESP-IDF Tools › Flash Frequency' }
    );
    if (picked) await setCfg('flashFreq', picked.label);
}

async function cmdSelectFlashSize() {
    if (checkBusy()) return;
    const picked = await vscode.window.showQuickPick(['1MB','2MB','4MB','8MB','16MB'].map(s => ({ label: s })),
        { title: 'ESP-IDF Tools › Flash Size' }
    );
    if (picked) await setCfg('flashSize', picked.label);
}

async function cmdToggleCompressedUpload() {
    if (checkBusy()) return;
    await setCfg('useCompressedUpload', !(cfg('useCompressedUpload') ?? true));
}

async function cmdSelectBeforeFlashing() {
    if (checkBusy()) return;
    const picked = await vscode.window.showQuickPick([
        { label: 'default_reset',   description: 'Reset to bootloader (default)' },
        { label: 'no_reset',        description: 'No reset' },
        { label: 'no_reset_no_sync',description: 'No reset, no sync' },
    ], { title: 'ESP-IDF Tools › Chip Reset Before Flash (esptool --before)' });
    if (picked) await setCfg('beforeFlashing', picked.label);
}

async function cmdSelectAfterFlashing() {
    if (checkBusy()) return;
    const picked = await vscode.window.showQuickPick([
        { label: 'hard_reset', description: 'Hard reset after flashing (default)' },
        { label: 'no_reset',   description: 'No reset' },
    ], { title: 'ESP-IDF Tools › Chip Reset After Flash (esptool --after)' });
    if (picked) await setCfg('afterFlashing', picked.label);
}

// ╔══════════════════════════════════════════════════════════════════╗
// ║  FILESYSTEM IMAGE GENERATORS                                        ║
// ╚══════════════════════════════════════════════════════════════════╝

async function fsImagePreflight(fsLabel, defaultFlashSize) {
    if (checkBusy()) return null;
    const pythonCmd = await Python.getPythonCmd();
    if (!pythonCmd) return null;
    const idfPath = getValidIdfPath();
    if (!idfPath) {
        const ans = await vscode.window.showErrorMessage(
            `ESP ${fsLabel}: ESP8266 RTOS SDK not found. Set up SDK first.`,
            'Set up SDK'
        );
        if (ans === 'Set up SDK') vscode.commands.executeCommand('esp.selectIdf');
        return null;
    }
    const root = getActiveRoot();
    if (!root) { warnNoProject(); return null; }
    if (!fs.existsSync(path.join(root, 'CMakeLists.txt')) && !fs.existsSync(path.join(root, 'sdkconfig'))) {
        vscode.window.showErrorMessage(`ESP ${fsLabel}: No CMakeLists.txt or sdkconfig found. Is this an ESP-IDF project?`);
        return null;
    }
    const folderUri = await vscode.window.showOpenDialog({
        canSelectFiles: false,
        canSelectFolders: true,
        canSelectMany: false,
        openLabel: `Select folder to pack into ${fsLabel} image`,
        title: `${fsLabel}: Select source folder`,
        defaultUri: vscode.Uri.file(root),
    });
    if (!folderUri || !folderUri[0]) return null;
    const dataDir = folderUri[0].fsPath;

    const sdkVal = (key, def) => getSdkconfigValue(root, key) || def;
    const flashSizeStr = sdkVal('CONFIG_ESPTOOLPY_FLASHSIZE', defaultFlashSize);
    const flashBytes = FLASH_SIZE_MAP[flashSizeStr] || FLASH_SIZE_MAP[defaultFlashSize] || 2097152;

    return { pythonCmd, idfPath, root, dataDir, flashBytes, flashSizeStr, sdkVal };
}

async function fsImageSelectSize(fsLabel, flashBytes, blockSize, allowAuto = true) {
    const presets = [64, 128, 256, 512, 1024, 2048, 4096]
        .map(kb => kb * 1024)
        .filter(b => b <= flashBytes && (blockSize ? b % blockSize === 0 : true))
        .map(b => ({
            label: b >= 1048576 ? `${b/1048576} MB` : `${b/1024} KB`,
            description: `${b} bytes (0x${b.toString(16).toUpperCase()})`,
            bytes: b
        }));

    const sizeItems = [
        ...(allowAuto ? [{
            label: '$(wand) Auto',
            description: `Let ${fsLabel} calculate the minimum required size`,
            bytes: null
        }] : []),
        ...presets,
        {
            label: '$(pencil) Enter manually...',
            description: 'Type exact size in bytes, KB/MB or hex',
            bytes: 'manual'
        }
    ];

    const pickedSize = await vscode.window.showQuickPick(sizeItems, {
        title: `${fsLabel}: Select image size`,
        placeHolder: allowAuto ? 'Auto — recommended if you are not sure' : 'Select image size'
    });
    if (!pickedSize) return null;

    if (pickedSize.bytes === 'manual') {
        const input = await vscode.window.showInputBox({
            title: `${fsLabel}: Enter image size`,
            prompt: 'Bytes, KB/MB or hex — e.g. 1048576 or 1M or 0x100000',
            placeHolder: '0x100000',
            validateInput: v => {
                v = v.trim();
                const n = /^0[xX]/.test(v) ? parseInt(v, 16)
                    : /^\d+[Mm]$/.test(v) ? parseInt(v) * 1048576
                    : /^\d+[Kk]$/.test(v) ? parseInt(v) * 1024
                    : parseInt(v);
                if (isNaN(n) || n <= 0) return 'Enter a positive number';
                if (blockSize && n % blockSize !== 0) return `Size must be a multiple of block size (${blockSize} bytes)`;
                if (n > flashBytes) return `Exceeds flash size (${flashBytes} bytes)`;
                return null;
            }
        });
        if (!input) return null;
        const v = input.trim();
        const n = /^0[xX]/.test(v) ? parseInt(v, 16)
            : /^\d+[Mm]$/.test(v) ? parseInt(v) * 1048576
            : /^\d+[Kk]$/.test(v) ? parseInt(v) * 1024
            : parseInt(v);
        return String(n);
    } else if (pickedSize.bytes !== null) {
        return String(pickedSize.bytes);
    }
    return 'detect';
}

function fsImageRunTerminal(termName, root, pythonCmd, scriptPath, args, markerFile, idfPath) {
    // #40: Removed checkBusy() — callers already check busy state before calling us
    setBusy(termName);
    const t = getTerm(termName);
    t.show(true);

    const pycmd = pythonCmd.replace(/^& /, '').replace(/^"|"$/g, '');
    const envPrefix = idfPath ? buildIdfEnvPrefix(idfPath, pythonCmd) : '';
    const parts = IS_WIN
        ? [`Set-Location ${q(root)}`, envPrefix, `& ${q(pycmd)} ${q(scriptPath)} ${args}` + buildMarkerCmd(markerFile)]
        : [`cd ${q(root)}`, envPrefix, `${q(pycmd)} ${q(scriptPath)} ${args}` + buildMarkerCmd(markerFile)];
    t.sendText(buildCmd(parts.filter(Boolean)));
    return watchCommandDone(markerFile, termName).then(
        exitCode => { clearBusy(); return exitCode; },
        () => { clearBusy(); return -1; }
    );
}

async function handleFsImageResult(exitCode, fsLabel, retryFn) {
    if (exitCode === 2) {
        const retry = await vscode.window.showWarningMessage(
            `${fsLabel}: The selected image size is too small for the data.`,
            'Retry with auto-size',
            'Cancel'
        );
        if (retry === 'Retry with auto-size') {
            await retryFn();
        }
    } else if (exitCode !== 0 && exitCode !== -1) {
        vscode.window.showErrorMessage(`${fsLabel}: Image generation failed (exit code ${exitCode}). Check the terminal for details.`);
    }
}

async function cmdMakeSpiffs() {
    const pre = await fsImagePreflight('SPIFFS', '2MB');
    if (!pre) return;
    const { pythonCmd, idfPath, root, dataDir, flashBytes, sdkVal } = pre;

    const spiffsgenScript = IdfRunner.getSpiffsgenScript();
    const pageSize   = sdkVal('CONFIG_SPIFFS_PAGE_SIZE', '256');
    const blockSize  = sdkVal('CONFIG_WL_SECTOR_SIZE', '4096');
    const objNameLen = '32';
    const metaLen    = '4';

    log(`[spiffs] page=${pageSize} block=${blockSize} obj-name-len=${objNameLen} meta-len=${metaLen}`);
    const outBin = path.join(root, path.basename(dataDir) + '_spiffs.bin');

    const BLOCK = parseInt(blockSize) || 4096;
    const imageSizeArg = await fsImageSelectSize('SPIFFS', flashBytes, BLOCK);
    if (imageSizeArg === null) return;

    const positional = imageSizeArg && imageSizeArg !== 'detect'
        ? `${imageSizeArg} ${q(dataDir)} ${q(outBin)}`
        : `${q(dataDir)} ${q(outBin)}`;
    const spiffsArgs = `--page-size ${pageSize} --block-size ${blockSize} --obj-name-len ${objNameLen} --meta-len ${metaLen} --use-magic --use-magic-len --aligned-obj-ix-tables`;

    const markerFile = path.join(os.tmpdir(), `esp_spiffs_${Date.now()}.tmp`);
    const sizeLabel = (!imageSizeArg || imageSizeArg === 'detect') ? 'auto size' : `${(parseInt(imageSizeArg)/1024).toFixed(0)} KB`;
    vscode.window.showInformationMessage(`ESP SPIFFS: Building image (${sizeLabel}) → ${path.basename(outBin)}`);
    const exitCode = await fsImageRunTerminal('ESP › Make SPIFFS', root, pythonCmd, spiffsgenScript, `${positional} ${spiffsArgs}`, markerFile, idfPath);
    await handleFsImageResult(exitCode, 'SPIFFS', async () => {
        const autoPositional = `${q(dataDir)} ${q(outBin)}`;
        const autoMarkerFile = path.join(os.tmpdir(), `esp_spiffs_auto_${Date.now()}.tmp`);
        vscode.window.showInformationMessage(`ESP SPIFFS: Retrying with auto-size → ${path.basename(outBin)}`);
        await fsImageRunTerminal('ESP › Make SPIFFS', root, pythonCmd, spiffsgenScript, `${autoPositional} ${spiffsArgs}`, autoMarkerFile, idfPath);
    });
}

async function cmdMakeFatfs() {
    const pre = await fsImagePreflight('FATFS', '4MB');
    if (!pre) return;
    const { pythonCmd, idfPath, root, dataDir, flashBytes, sdkVal } = pre;

    const fatfsgenScript = IdfRunner.getFatfsgenScript();
    const sectorSize = sdkVal('CONFIG_WL_SECTOR_SIZE', '4096');
    const secPerClus  = '1';
    const longNameSupport = true;

    log(`[fatfs] sector_size=${sectorSize} sectors_per_cluster=${secPerClus}`);

    const partitionSizeArg = await fsImageSelectSize('FATFS', flashBytes, null);
    if (partitionSizeArg === null) return;

    const wlItems = [
        { label: 'No wear levelling', description: 'Plain FATFS image', value: 'none' },
        { label: 'With wear levelling (perf)', description: `FATFS + WL layer, performance mode (sector_size ${sectorSize})`, value: 'perf' },
        { label: 'With wear levelling (safe)', description: `FATFS + WL layer, safe mode (sector_size ${sectorSize})`, value: 'safe' },
    ];
    const pickedWl = await vscode.window.showQuickPick(wlItems, {
        title: 'FATFS: Wear levelling mode',
        placeHolder: 'No wear levelling (most common)'
    });
    if (!pickedWl) return;

    const isWl = pickedWl.value !== 'none';
    const wlSuffix = pickedWl.value === 'perf' ? '_wl_p' : pickedWl.value === 'safe' ? '_wl_s' : '';
    const outBin = path.join(root, path.basename(dataDir) + '_fatfs' + wlSuffix + '.bin');

    const scriptToRun = isWl
        ? path.join(getGlobalCtx().extensionPath, 'scripts', 'wl_fatfsgen.py')
        : fatfsgenScript;

    // Resolve the partition size argument
    let resolvedSize = partitionSizeArg;
    if (!resolvedSize || resolvedSize === 'detect') {
        // Auto mode: pass 'detect' for both WL and non-WL.
        // Both fatfsgen.py and wl_fatfsgen.py handle --partition_size detect
        // by auto-calculating the minimum required size.
        resolvedSize = 'detect';
    }

    const buildFatfs = async (sizeArg) => {
        let fatfsArgs = `--output_file ${q(outBin)} --partition_size ${sizeArg} --sector_size ${sectorSize} --sectors_per_cluster ${secPerClus}`;
        if (longNameSupport) fatfsArgs += ' --long_name_support';
        if (isWl) fatfsArgs += ` --wl_mode ${pickedWl.value}`;
        fatfsArgs = q(dataDir) + ' ' + fatfsArgs;

        const markerFile = path.join(os.tmpdir(), `esp_fatfs_${Date.now()}.tmp`);
        const sizeLabel = (sizeArg === 'detect') ? 'auto size' : `${(parseInt(sizeArg)/1024).toFixed(0)} KB`;
        const wlLabel = isWl ? ` (WL ${pickedWl.value})` : '';
        vscode.window.showInformationMessage(`ESP FATFS: Building image${wlLabel} (${sizeLabel}) → ${path.basename(outBin)}`);
        return fsImageRunTerminal('ESP › Make FATFS', root, pythonCmd, scriptToRun, fatfsArgs, markerFile, idfPath);
    };

    const exitCode = await buildFatfs(resolvedSize);
    await handleFsImageResult(exitCode, 'FATFS', async () => {
        vscode.window.showInformationMessage(`ESP FATFS: Retrying with auto-size → ${path.basename(outBin)}`);
        await buildFatfs('detect');
    });
}

async function cmdMakeLittlefs() {
    const pre = await fsImagePreflight('LittleFS', '4MB');
    if (!pre) return;
    const { pythonCmd, idfPath, root, dataDir, flashBytes, sdkVal } = pre;

    const littlefsgenScript = IdfRunner.getLittlefsgenScript();
    const blockSize = sdkVal('CONFIG_WL_SECTOR_SIZE', '4096');
    const nameMax = '32';

    log(`[littlefs] block_size=${blockSize} name_max=${nameMax}`);
    const outBin = path.join(root, path.basename(dataDir) + '_littlefs.bin');

    const imageSizeArg = await fsImageSelectSize('LittleFS', flashBytes, parseInt(blockSize));
    if (imageSizeArg === null) return;

    const buildLittlefs = async (sizeArg) => {
        let lfsArgs = q(dataDir) + ' ' + q(outBin);
        if (sizeArg && sizeArg !== 'detect') {
            lfsArgs += ` --image_size ${sizeArg}`;
        }
        lfsArgs += ` --block_size ${blockSize} --name_max ${nameMax}`;
        const markerFile = path.join(os.tmpdir(), `esp_littlefs_${Date.now()}.tmp`);
        const sizeLabel = (!sizeArg || sizeArg === 'detect') ? 'auto size' : `${(parseInt(sizeArg)/1024).toFixed(0)} KB`;
        vscode.window.showInformationMessage(`ESP LittleFS: Building image (${sizeLabel}) → ${path.basename(outBin)}`);
        return fsImageRunTerminal('ESP › Make LittleFS', root, pythonCmd, littlefsgenScript, lfsArgs, markerFile, idfPath);
    };

    const exitCode = await buildLittlefs(imageSizeArg);
    await handleFsImageResult(exitCode, 'LittleFS', async () => {
        vscode.window.showInformationMessage(`ESP LittleFS: Retrying with auto-size → ${path.basename(outBin)}`);
        await buildLittlefs(null);  // null = auto mode (no --image_size)
    });
}

// ╔══════════════════════════════════════════════════════════════════╗
// ║  FLASH FILESYSTEM IMAGE: esptool.py write_flash                    ║
// ╚══════════════════════════════════════════════════════════════════╝
function parsePartitionCsvForFsParts(root, subtypes) {
    const csvFilename = getPartitionCsvFilename(root);
    const csvPath = path.join(root, csvFilename);
    if (!fs.existsSync(csvPath)) return [];

    const results = [];
    try {
        const csv = fs.readFileSync(csvPath, 'utf8');
        for (const line of csv.split('\n')) {
            const trimmed = line.trim();
            if (!trimmed || trimmed.startsWith('#')) continue;
            const parts = trimmed.split(',').map(s => s.trim());
            if (parts.length < 5) continue;
            const subtype = (parts[2] || '').toLowerCase();
            // Match: spiffs, fat, fatfs, littlefs
            if (subtypes.includes(subtype)) {
                results.push({ name: parts[0], type: parts[1], subtype, offset: parts[3], size: parts[4] });
            }
        }
    } catch {}
    return results;
}

function getEsptoolPath() {
    const idfPath = getValidIdfPath();
    if (!idfPath) return null;
    // esptool.py lives in the SDK components
    const candidates = [
        path.join(idfPath, 'components', 'esptool_py', 'esptool', 'esptool.py'),
        path.join(idfPath, 'tools', 'esptool.py'),
    ];
    for (const p of candidates) {
        if (fs.existsSync(p)) return p;
    }
    // Try to find it in espressif tools
    const espTools = path.join(os.homedir(), '.espressif');
    try {
        const esptoolDir = path.join(espTools, 'tools', 'esptool');
        if (fs.existsSync(esptoolDir)) {
            const versions = fs.readdirSync(esptoolDir).sort().reverse();
            for (const ver of versions) {
                const candidate = path.join(esptoolDir, ver, 'esptool.py');
                if (fs.existsSync(candidate)) return candidate;
            }
        }
    } catch {}
    return null;
}

async function cmdFlashFsImage(fsLabel, subtypes, binSuffix) {
    if (checkBusy()) return;

    // #37: Use a helper that ensures clearBusy() on every early return
    const _earlyReturn = () => { clearBusy(); };
    setBusy(`Flash ${fsLabel}`);

    try {
    const root = getActiveRoot();
    if (!root) { _earlyReturn(); warnNoProject(); return; }

    const pythonCmd = await Python.getPythonCmd(true);
    if (!pythonCmd) { _earlyReturn(); return; }

    const idfPath = getValidIdfPath();
    if (!idfPath) {
        _earlyReturn();
        vscode.window.showErrorMessage('ESP: IDF_PATH not set or invalid!');
        return;
    }

    // #24: Check tools (esptool etc.) before proceeding
    const toolsOk = await IdfRunner.checkToolsOrPrompt(idfPath, pythonCmd);
    if (!toolsOk) { _earlyReturn(); return; }

    // Check Python dependencies before running esptool
    if (!await Python.checkPythonDeps(idfPath, pythonCmd)) { _earlyReturn(); return; }

    // 1. Find matching partitions in CSV
    const fsParts = parsePartitionCsvForFsParts(root, subtypes);

    if (fsParts.length === 0) {
        _earlyReturn();
        const ans = await vscode.window.showErrorMessage(
            `ESP Flash ${fsLabel}: No ${fsLabel} partition found in partition table.\n` +
            'Add a partition with the correct SubType first.',
            'Open Partition Editor', 'Cancel'
        );
        if (ans === 'Open Partition Editor') {
            vscode.commands.executeCommand('esp.partitionEditor');
        }
        return;
    }

    // 2. Find .bin files in project root
    const buildDir = path.join(root, 'build');
    const searchDirs = [root];
    if (fs.existsSync(buildDir)) searchDirs.push(buildDir);

    let foundBins = [];
    for (const dir of searchDirs) {
        try {
            const files = fs.readdirSync(dir).filter(f => f.endsWith(binSuffix));
            for (const f of files) {
                foundBins.push(path.join(dir, f));
            }
        } catch {}
    }

    if (foundBins.length === 0) {
        const uris = await vscode.window.showOpenDialog({
            canSelectFiles: true,
            canSelectFolders: false,
            canSelectMany: false,
            title: `Flash ${fsLabel}: Select .bin file`,
            defaultUri: fs.existsSync(buildDir) ? vscode.Uri.file(buildDir) : vscode.Uri.file(root),
            filters: { 'Binary files': ['bin'], 'All files': ['*'] },
            openLabel: 'Select firmware',
        });
        if (!uris?.length) { _earlyReturn(); return; }
        foundBins = [uris[0].fsPath];
    }

    // 3. Pick partition (if multiple)
    let selectedPart;
    if (fsParts.length === 1) {
        selectedPart = fsParts[0];
    } else {
        const items = fsParts.map(p => ({
            label: `$(package) ${p.name}`,
            description: `${p.subtype} — offset ${p.offset}, size ${p.size}`,
            detail: `Partition for ${fsLabel} flash`,
            part: p,
        }));
        const picked = await vscode.window.showQuickPick(items, {
            title: `Flash ${fsLabel}: Select target partition`,
            placeHolder: 'Choose which partition to flash to',
        });
        if (!picked) { _earlyReturn(); return; }
        selectedPart = picked.part;
    }

    // 4. Pick bin file (if multiple)
    let selectedBin;
    if (foundBins.length === 1) {
        selectedBin = foundBins[0];
    } else {
        const binItems = foundBins.map(f => ({
            label: `$(file-binary) ${path.basename(f)}`,
            description: path.dirname(f).replace(root, '.'),
            detail: f,
            binPath: f,
        }));
        const picked = await vscode.window.showQuickPick(binItems, {
            title: `Flash ${fsLabel}: Select .bin file`,
            placeHolder: 'Choose which .bin file to flash',
        });
        if (!picked) { _earlyReturn(); return; }
        selectedBin = picked.binPath;
    }

    // 5. Get port
    let port = cfg('comPort');
    if (!port) {
        port = await Ports.cmdSelectPort();
        if (!port) { _earlyReturn(); return; }
    }

    // #46: Validate port for shell metacharacters
    if (port && !/^[a-zA-Z0-9./\\_-]+$/.test(port)) {
        _earlyReturn();
        vscode.window.showErrorMessage('ESP: Invalid port name! Shell metacharacters are not allowed.');
        return;
    }

    // #25: Verify port is still available
    if (port) {
        const portHolder = { port };
        const portOk = await Ports.confirmPortOrReselect(portHolder);
        if (!portOk) { _earlyReturn(); return; }
        port = portHolder.port;
        if (port !== cfg('comPort')) await setCfg('comPort', port);
    }

    // 6. Confirm
    const confirmed = await vscode.window.showWarningMessage(
        `Flash ${path.basename(selectedBin)} to ${fsLabel} partition "${selectedPart.name}" at offset ${selectedPart.offset} on port ${port}?`,
        { modal: true, detail: `This will overwrite the ${fsLabel} partition on the device.\nOffset: ${selectedPart.offset}\nPort: ${port}` },
        'Flash'
    );
    if (confirmed !== 'Flash') { _earlyReturn(); return; }

    // 7. Run esptool.py write_flash
    const esptoolPath = getEsptoolPath();
    if (!esptoolPath) {
        _earlyReturn();
        vscode.window.showErrorMessage('ESP: esptool.py not found! Check that the ESP8266_RTOS_SDK is installed correctly.');
        return;
    }
    const termName = `ESP › Flash ${fsLabel}`;
    const t = getTerm(termName);
    t.show(true);

    const pycmd = pythonCmd.replace(/^& /, '').replace(/^"|"$/g, '');

    // #22: Respect overrideFlashConfig — only include flash params in manual mode
    const overrideFlash = cfg('overrideFlashConfig');
    const beforeFlash = cfg('beforeFlashing') || 'default_reset';
    const afterFlash  = cfg('afterFlashing')  || 'hard_reset';
    // --before / --after are TOP-LEVEL esptool options (not write_flash subcommand
    // options). They MUST appear BEFORE the 'write_flash' subcommand on the CLI.
    const esptoolArgs = ['--port', port,
        '--before', beforeFlash, '--after', afterFlash];

    if (overrideFlash) {
        const baud = cfg('flashBaud') || 115200;
        const compressed = cfg('useCompressedUpload') ?? true;
        const flashMode = cfg('flashMode') || 'dio';
        const flashFreq = cfg('flashFreq') || '40m';
        const flashSize = cfg('flashSize') || '2MB';
        esptoolArgs.push('--baud', String(baud));
        esptoolArgs.push('write_flash',
            '--flash_mode', flashMode,
            '--flash_freq', flashFreq,
            '--flash_size', flashSize,
            compressed ? '--compress' : '--no-compress',
        );
    } else {
        // Menuconfig mode: let esptool read flash settings from binary image
        esptoolArgs.push('write_flash');
    }

    esptoolArgs.push(selectedPart.offset, q(selectedBin));

    const envPrefix = buildIdfEnvPrefix(idfPath, pythonCmd);
    const markerFile = path.join(os.tmpdir(), `esp_flash_fs_${Date.now()}.tmp`);

    if (IS_WIN) {
        const cmdParts = [
            `Set-Location ${q(root)}`,
            envPrefix,
            `& ${q(pycmd)} ${q(esptoolPath || 'esptool.py')} ${esptoolArgs.join(' ')}`,
        ];
        t.sendText(cmdParts.join('; ') + buildMarkerCmd(markerFile));
    } else {
        const cmdParts = [
            `cd ${q(root)}`,
            envPrefix,
            `${q(pycmd)} ${q(esptoolPath || 'esptool.py')} ${esptoolArgs.join(' ')}`,
        ];
        t.sendText(cmdParts.join(' && ') + buildMarkerCmd(markerFile));
    }

    log(`[Flash ${fsLabel}] writing ${selectedBin} to offset ${selectedPart.offset} on ${port} (overrideFlash=${overrideFlash})`);

    watchCommandDone(markerFile, termName).then(exitCode => {
        if (exitCode === 0) {
            vscode.window.showInformationMessage(`✅ Flash ${fsLabel}: ${path.basename(selectedBin)} written to "${selectedPart.name}" at ${selectedPart.offset}!`);
            log(`[Flash ${fsLabel}] ✅ OK`);
            // Auto-start monitor if configured
            const postAction = cfg('postFlashFsAction') || 'none';
            if (postAction === 'monitor') {
                log(`[Flash ${fsLabel}] starting monitor (postFlashFsAction=monitor)`);
                clearBusy(); // Must clear before runFlash — it checks checkBusy() first
                Flash.runFlash('monitor');
                return; // monitor will set its own busy state
            }
        } else if (exitCode > 0) {
            vscode.window.showErrorMessage(`❌ Flash ${fsLabel} failed (exit ${exitCode}). Check terminal for details.`);
            log(`[Flash ${fsLabel}] ❌ failed (exit ${exitCode})`);
        }
        clearBusy();
    }).catch(() => clearBusy());

    } catch (e) {
        clearBusy();
        log(`[Flash ${fsLabel}] error: ${e.message}`);
    }
}

/**
 * Detect filesystem type(s) from CMakeLists.txt.
 * Looks for the block:
 *   # ESP8266 Tools: partition bin links -- BEGIN
 *   esptool_py_flash_project_args(storage 0xB0000 "data_spiffs.bin" FLASH_IN_PROJECT)
 *   # ESP8266 Tools: partition bin links -- END
 * Returns array of { fsType:'spiffs'|'fatfs'|'littlefs', partitionName, offset, binPath } or null.
 * #38: Returns ALL found FS entries so caller can prompt user to choose.
 */
function detectFsTypeFromCmake(root) {
    const cmakePath = path.join(root, 'CMakeLists.txt');
    if (!fs.existsSync(cmakePath)) return null;

    try {
        const content = fs.readFileSync(cmakePath, 'utf8');
        const beginMarker = '# ESP8266 Tools: partition bin links -- BEGIN';
        const endMarker   = '# ESP8266 Tools: partition bin links -- END';
        const beginIdx = content.indexOf(beginMarker);
        const endIdx   = content.indexOf(endMarker);
        if (beginIdx < 0 || endIdx < 0 || endIdx <= beginIdx) return null;

        const block = content.substring(beginIdx, endIdx + endMarker.length);

        // Parse ALL esptool_py_flash_project_args entries (use matchAll for multiple FS partitions)
        const allMatches = [...block.matchAll(/esptool_py_flash_project_args\s*\(\s*(\S+)\s+(0x[0-9a-fA-F]+)\s+"([^"]+)"/g)];
        if (allMatches.length === 0) return null;

        // Find all FS-type entries
        const fsEntries = [];
        for (const m of allMatches) {
            const partitionName = m[1];
            const offset        = m[2];
            const binPath       = m[3];
            const binLower      = binPath.toLowerCase();

            let fsType = null;
            if (binLower.includes('spiffs'))     fsType = 'spiffs';
            else if (binLower.includes('littlefs')) fsType = 'littlefs';
            else if (binLower.includes('fatfs') || binLower.includes('fat')) fsType = 'fatfs';

            if (fsType) fsEntries.push({ fsType, partitionName, offset, binPath });
        }

        if (fsEntries.length === 0) return null;
        return fsEntries; // #38: return ALL FS entries
    } catch {
        return null;
    }
}

async function cmdFlashFileSystem() {
    if (checkBusy()) return;

    const root = getActiveRoot();
    if (!root) { warnNoProject(); return; }

    // 1. Try auto-detection from CMakeLists.txt
    // #38: detectFsTypeFromCmake now returns an array of all FS entries
    const cmakeEntries = detectFsTypeFromCmake(root);

    // Map of fsType → { label, subtypes, binSuffix }
    const FS_MAP = {
        spiffs:   { label: 'SPIFFS',   subtypes: ['spiffs'],           binSuffix: '_spiffs.bin'   },
        fatfs:    { label: 'FATFS',     subtypes: ['fat', 'fatfs'],      binSuffix: '_fatfs.bin'    },
        littlefs: { label: 'LittleFS',  subtypes: ['littlefs'],          binSuffix: '_littlefs.bin' },
    };

    if (cmakeEntries && cmakeEntries.length > 0) {
        if (cmakeEntries.length === 1) {
            // Single FS partition — auto-detect straightforward
            const entry = cmakeEntries[0];
            const fsInfo = FS_MAP[entry.fsType];
            const autoDetect = await vscode.window.showInformationMessage(
                `ESP: Auto-detected filesystem: ${fsInfo.label} (from CMakeLists.txt)`,
                'Continue', 'Choose manually'
            );
            if (autoDetect === 'Choose manually') {
                // Fall through to manual selection
            } else if (autoDetect === 'Continue') {
                return cmdFlashFsImage(fsInfo.label, fsInfo.subtypes, fsInfo.binSuffix);
            } else {
                return; // cancelled
            }
        } else {
            // #38: Multiple FS partitions — let user choose which one
            const pickItems = cmakeEntries.map(e => {
                const fsInfo = FS_MAP[e.fsType];
                return {
                    label: `$(cloud-upload) ${fsInfo.label}`,
                    description: `${e.partitionName} — offset ${e.offset}`,
                    detail: `Auto-detected from CMakeLists.txt: ${e.binPath}`,
                    value: e.fsType,
                };
            });
            pickItems.push({
                label: '$(list-unordered) Choose manually...',
                description: 'Select filesystem type manually',
                detail: 'Skip auto-detection',
                value: '_manual',
            });
            const picked = await vscode.window.showQuickPick(pickItems, {
                title: 'Flash File System: Multiple partitions detected',
                placeHolder: 'Select which filesystem to flash',
            });
            if (!picked) return;
            if (picked.value === '_manual') {
                // Fall through to manual selection
            } else {
                const fsInfo = FS_MAP[picked.value];
                return cmdFlashFsImage(fsInfo.label, fsInfo.subtypes, fsInfo.binSuffix);
            }
        }
    }

    // 2. Manual selection (or auto-detect failed)
    // #49: Check partition table first — only show FS types that the project actually uses
    const availableFsTypes = [];
    for (const [key, val] of Object.entries(FS_MAP)) {
        const parts = parsePartitionCsvForFsParts(root, val.subtypes);
        if (parts.length > 0) {
            availableFsTypes.push({ key, val, parts });
        }
    }

    if (availableFsTypes.length === 0) {
        const ans = await vscode.window.showErrorMessage(
            'ESP Flash File System: No filesystem partitions found in partition table.\n' +
            'Add a filesystem partition (SPIFFS, FATFS, or LittleFS) first.',
            'Open Partition Editor', 'Cancel'
        );
        if (ans === 'Open Partition Editor') {
            vscode.commands.executeCommand('esp.partitionEditor');
        }
        return;
    }

    if (availableFsTypes.length === 1) {
        // Only one FS type has partitions — flash it directly, no need to ask
        const { val: fsInfo } = availableFsTypes[0];
        return cmdFlashFsImage(fsInfo.label, fsInfo.subtypes, fsInfo.binSuffix);
    }

    // Multiple FS types have partitions — let user choose which one
    const items = availableFsTypes.map(({ key, val, parts }) => ({
        label: `$(cloud-upload) ${val.label}`,
        description: `Flash ${val.label} .bin to partition`,
        detail: `${parts.length} partition(s): ${parts.map(p => p.name).join(', ')}`,
        value: key,
    }));

    const picked = await vscode.window.showQuickPick(items, {
        title: 'Flash File System: Select filesystem type',
        placeHolder: 'Choose filesystem type',
    });
    if (!picked) return;

    const fsInfo = FS_MAP[picked.value];
    return cmdFlashFsImage(fsInfo.label, fsInfo.subtypes, fsInfo.binSuffix);
}

async function cmdResetConfig() {
    if (checkBusy()) return;
    if (!await Python.requireReady()) return;
    const root = getActiveRoot();
    if (!root) { warnNoProject(); return; }

    const sdkconfig    = path.join(root, 'sdkconfig');
    const sdkconfigOld = path.join(root, 'sdkconfig.old');

    const exists    = fs.existsSync(sdkconfig);
    const existsOld = fs.existsSync(sdkconfigOld);

    if (!exists && !existsOld) {
        vscode.window.showInformationMessage('ESP: No sdkconfig files found — nothing to reset.');
        return;
    }

    const files = [exists && 'sdkconfig', existsOld && 'sdkconfig.old'].filter(Boolean).join(' + ');
    const choice = await vscode.window.showWarningMessage(
        `ESP: Delete ${files}? All menuconfig settings will be reset to defaults on next build.`,
        { modal: true },
        'Delete', 'Cancel'
    );
    if (choice !== 'Delete') return;

    let deleted = [];
    try { if (exists)    { fs.unlinkSync(sdkconfig);    deleted.push('sdkconfig'); }    } catch (e) { vscode.window.showErrorMessage(`ESP: Failed to delete sdkconfig: ${e.message}`); return; }
    try { if (existsOld) { fs.unlinkSync(sdkconfigOld); deleted.push('sdkconfig.old'); } } catch (e) { log(`Failed to delete sdkconfig.old: ${e.message}`); vscode.window.showWarningMessage(`ESP: Could not delete sdkconfig.old: ${e.message}`); }

    // #27: Invalidate sdkconfig cache so stale values are not returned
    setSdkconfigCache(null);

    vscode.window.showInformationMessage(`ESP: Deleted ${deleted.join(' + ')}. Run Build to regenerate with defaults.`);
    log(`Reset Config: deleted ${deleted.join(', ')}`);
}

// ╔══════════════════════════════════════════════════════════════════╗
// ║  ACTIVATION / DEACTIVATION                                         ║
// ╚══════════════════════════════════════════════════════════════════╝
function activate(ctx) {
    setGlobalCtx(ctx);
    const provider = new TreeProvider.EspProvider();
    setProvider(provider);

    // Register busy state change callback to notify CMake editor panels
    H.setOnBusyChange((busy, name) => {
        CmakeEditor.notifyBusyState(busy, name);
    });

    const folders   = vscode.workspace.workspaceFolders;
    const savedRoot = ctx.workspaceState.get('espActiveRoot');
    if (savedRoot && folders?.find(f => f.uri.fsPath === savedRoot)) {
        setActiveRoot(savedRoot);
    }

    ctx.subscriptions.push(
        vscode.window.onDidCloseTerminal(closed => {
            const terms = getTerms();
            for (const [name, t] of Object.entries(terms)) {
                if (t === closed) {
                    delete terms[name];
                    log(`Terminal closed: "${name}"`);
                    const monitorTermNames = ['ESP › Monitor', 'ESP › Flash & Monitor', 'ESP › Erase & Flash & Monitor', 'ESP › App flash & Monitor', 'ESP › Bootloader flash & Monitor', 'ESP › Partition table flash & Monitor'];
                    if (monitorTermNames.includes(name)) {
                        setMonitorRunning(false);
                        clearBusy();
                        StatusBar.refreshMonitorButton();
                        log(`Monitor terminal killed — state reset`);
                    }
                    break;
                }
            }
        })
    );

    StatusBar.createStatusBar(ctx);

    if (IS_LINUX) checkDialoutGroup();

    let _autoGenTimer = null;
    const scheduleAutoGenerate = (delay = 1000) => {
        if (_autoGenTimer) clearTimeout(_autoGenTimer);
        _autoGenTimer = setTimeout(() => { _autoGenTimer = null; autoGenerateDevFiles(); }, delay);
    };

    scheduleAutoGenerate(2000);

    const treeView = vscode.window.createTreeView('esp8266-idf.projectView', { treeDataProvider: provider });

    setTimeout(() => {
        const startupIdfPath = getValidIdfPath();
        if (startupIdfPath) ensureVersionTxt(startupIdfPath);
        IdfRunner.checkEnvironment(true).then(ok => { if (ok) IdfRunner.checkAndInstallTools(); });
    }, 500);

    treeView.onDidCollapseElement(e => {
        if (e.element.id) ctx.workspaceState.update(`espGroupState_${e.element.id}`, vscode.TreeItemCollapsibleState.Collapsed);
    });
    treeView.onDidExpandElement(e => {
        if (e.element.id) ctx.workspaceState.update(`espGroupState_${e.element.id}`, vscode.TreeItemCollapsibleState.Expanded);
    });

    let _checkboxWriteQueue = Promise.resolve();
    treeView.onDidChangeCheckboxState(e => {
        if (checkBusy()) {
            provider.refresh();
            return;
        }
        const root = getActiveRoot();
        if (!root) return;
        _checkboxWriteQueue = _checkboxWriteQueue.then(() => {
            for (const [item, state] of e.items) {
                if (item._compName) {
                    const excluded = Components.readExcludedComponents(root);
                    const name = item._compName;
                    const isNowChecked = state === vscode.TreeItemCheckboxState.Checked;
                    if (isNowChecked && excluded.includes(name)) {
                        Components.writeExcludedComponents(root, excluded.filter(c => c !== name));
                        vscode.window.showInformationMessage(`ESP: Component "${name}" included in build`);
                    } else if (!isNowChecked && !excluded.includes(name)) {
                        excluded.push(name);
                        Components.writeExcludedComponents(root, excluded);
                        vscode.window.showInformationMessage(`ESP: Component "${name}" excluded from build`);
                    }
                }
            }
            provider.refresh();
        }).catch(() => {});
    });

    ctx.subscriptions.push(
        treeView,
        vscode.workspace.onDidChangeConfiguration(e => {
            if (!e.affectsConfiguration('esp8266-idf')) return;
            if (e.affectsConfiguration('esp8266-idf.idfPath')) {
                if (cfg('idfPath') === getIdfPathOverride()) setIdfPathOverride(null);
                setPythonCmdCache(null); setToolsVerified(false); setSdkVersionCache(null);

                IdfRunner.checkAndInstallTools();
                scheduleAutoGenerate();
            }
            if (e.affectsConfiguration('esp8266-idf.pythonPath')) {
                setPythonCmdCache(null); setToolsVerified(false);
            }
            provider.refresh();
            StatusBar.refreshStatusBar();
        }),
        vscode.workspace.onDidChangeWorkspaceFolders(() => {
            const current = vscode.workspace.workspaceFolders || [];
            if (!current.find(f => f.uri.fsPath === getActiveRoot())) {
                // Close all editor webviews before switching project
                CmakeEditor.closeAllCmakePanels();
                NewProjectEditor.closeNewProjectPanel();
                Components.closeAddComponentPanel();
                Components.closeEditComponentPanel();
                SettingsEditor.closeSettingsPanel();
                if (getPartitionPanel()) { getPartitionPanel().dispose(); setPartitionPanel(null); }
                setActiveRoot(current[0]?.uri.fsPath || null);
                if (getGlobalCtx()) ctx.workspaceState.update('espActiveRoot', getActiveRoot());
            }
            provider.refresh();
            scheduleAutoGenerate();
        }),
    );

    const sdkconfigWatcher = vscode.workspace.createFileSystemWatcher('**/sdkconfig');
    sdkconfigWatcher.onDidChange(uri => {
        setSdkconfigCache(null);
        const root = getActiveRoot();
        if (!root) return;
        const changedDir = path.dirname(uri.fsPath);
        if (changedDir !== root) return;
        if (getPushSdkconfigUpdate()) {
            setTimeout(() => { try { getPushSdkconfigUpdate()(); } catch {} }, 300);
        }
    });
    ctx.subscriptions.push(sdkconfigWatcher);

    const sdkconfigDefaultsWatcher = vscode.workspace.createFileSystemWatcher('**/sdkconfig.defaults');
    sdkconfigDefaultsWatcher.onDidChange(() => { setSdkconfigCache(null); });
    sdkconfigDefaultsWatcher.onDidCreate(() => { setSdkconfigCache(null); });
    ctx.subscriptions.push(sdkconfigDefaultsWatcher);

    const reg = (id, fn) => ctx.subscriptions.push(vscode.commands.registerCommand(id, fn));

    reg('esp.build',           () => Flash.runIdf(['build'],           'ESP › Build', true, {}, null, null, 'Build'));
    reg('esp.buildApp',        () => Flash.runIdf(['app'],             'ESP › Build App', true, {}, null, null, 'BuildApp'));
    reg('esp.buildBootloader', () => Flash.runIdf(['bootloader'],      'ESP › Build Bootloader', true, {}, null, null, 'BuildBootloader'));
    reg('esp.buildPartition',  () => Flash.runIdf(['partition_table'], 'ESP › Build Partition Table', true, {}, null, null, 'BuildPartition'));
    reg('esp.size',            () => Flash.runIdf(['size'],            'ESP › Size',            false));
    reg('esp.sizeComponents',  () => Flash.runIdf(['size-components'], 'ESP › Size Components', false));
    reg('esp.sizeFiles',       () => Flash.runIdf(['size-files'],      'ESP › Size Files',      false));
    reg('esp.menuconfig',      () => Flash.runIdf(['menuconfig'],      'ESP › Menuconfig'));
    reg('esp.reconfigure',     () => Flash.runIdf(['reconfigure'],     'ESP › Reconfigure'));
    reg('esp.resetConfig',     async () => { await cmdResetConfig(); provider.refresh(); });
    reg('esp.clean',           () => Flash.runIdf(['clean'],           'ESP › Clean'));
    reg('esp.fullclean',       async () => {
        const postAction = cfg('postBuildAction');
        if (postAction === 'flash' || postAction === 'app_flash') {
            const ans = await vscode.window.showWarningMessage(
                'ESP: Full Clean deletes build output including flasher_args.json. ' +
                'The next Build + Flash will run reconfigure first automatically.',
                'Continue', 'Cancel'
            );
            if (ans !== 'Continue') return;
        }
        Flash.runIdf(['fullclean'], 'ESP › Full Clean');
    });

    reg('esp.flash',           () => Flash.runWithPostFlash('flash', 'Flash'));
    reg('esp.flashMonitor',    () => Flash.runFlash('flash_monitor'));
    reg('esp.monitor',         () => Flash.runFlash('monitor'));
    reg('esp.flashApp',        () => Flash.runWithPostFlash('app-flash', 'FlashApp'));
    reg('esp.flashBootloader', () => Flash.runWithPostFlash('bootloader-flash', 'FlashBootloader'));
    reg('esp.flashPartition',  () => Flash.runWithPostFlash('partition_table-flash', 'FlashPartition'));
    reg('esp.eraseFlash',      () => Flash.runFlash('erase_flash'));
    reg('esp.stopMonitor',     () => Flash.cmdStopMonitor());

    reg('esp.spiffs',          () => cmdMakeSpiffs());
    reg('esp.fatfs',           () => cmdMakeFatfs());
    reg('esp.littlefs',        () => cmdMakeLittlefs());
    reg('esp.flashFileSystem', () => cmdFlashFileSystem());
    reg('esp.addComponent',    async () => { await Components.cmdAddComponent(); provider.refresh(); });
    reg('esp.deleteComponent', async (item) => { await Components.cmdDeleteComponent(item); provider.refresh(); });
    reg('esp.editComponent',   async (item) => { await CmakeEditor.cmdCmakeEditorComponent(item); provider.refresh(); });
    reg('esp.partitionEditor', () => PartitionEditor.cmdPartitionEditor());

    // CMake Editor commands
    reg('esp.cmakeEditorMain',      () => CmakeEditor.cmdCmakeEditorMain());
    reg('esp.cmakeEditorComponent', async (item) => { await CmakeEditor.cmdCmakeEditorComponent(item); provider.refresh(); });
    reg('esp.cmakeEditorRoot',      () => CmakeEditor.cmdCmakeEditorRoot());

    // OTA Flash commands
    reg('esp.otaFlash',  async () => { await OtaFlash.cmdOtaFlash();  provider.refresh(); });
    reg('esp.otaSwitch', async () => { await OtaFlash.cmdOtaSwitch(); provider.refresh(); });
    reg('esp.otaRead',   async () => { await OtaFlash.cmdOtaReadOtadata(); });
    reg('esp.otaErase',  async () => { await OtaFlash.cmdOtaErase();  provider.refresh(); });

    reg('esp.generateIntelliSense', async () => { await cmdGenerateIntelliSense(); });
    reg('esp.generateTasks',        async () => { await cmdGenerateTasks(); });

    reg('esp.createProject',  async () => { await cmdCreateProject();  provider.refresh(); });
    reg('esp.editProject',    async () => { await cmdEditProject(); provider.refresh(); });
    reg('esp.clearProject',   () => {
        if (checkBusy()) return;
        setActiveRoot(null);
        setPortCache({ data: [], timestamp: 0 });
        if (getGlobalCtx()) getGlobalCtx().workspaceState.update('espActiveRoot', null);
        provider.refresh();
        StatusBar.refreshStatusBar();
    });
    reg('esp.selectPort',     async () => { const p = await Ports.cmdSelectPort();  provider.refresh(); StatusBar.refreshStatusBar(); return p; });
    reg('esp.selectIdf',      async () => { await IdfRunner.cmdFixSdk();  provider.refresh(); StatusBar.refreshStatusBar(); });
    reg('esp.selectProject',  async () => { await cmdSelectProject();  provider.refresh(); });
    reg('esp.configureBuild',       async () => { await SettingsEditor.cmdSettingsEditor('build');     provider.refresh(); });
    reg('esp.configureBuildSimple', async () => { await SettingsEditor.cmdSettingsEditor('build');     provider.refresh(); });
    reg('esp.configureFlash',    async () => { await SettingsEditor.cmdSettingsEditor('flash');     provider.refresh(); });
    reg('esp.configureFlashApp', async () => { await SettingsEditor.cmdSettingsEditor('flash');     provider.refresh(); });
    reg('esp.configureFlashFs',  async () => { await SettingsEditor.cmdSettingsEditor('flashfs');   provider.refresh(); });
    reg('esp.toggleOverride', async () => { if (checkBusy()) return; await setCfg('overrideFlashConfig', !cfg('overrideFlashConfig')); provider.refresh(); StatusBar.refreshStatusBar(); });
    reg('esp.selectFlashBaud',         async () => { await cmdSelectFlashBaud();         provider.refresh(); });
    reg('esp.selectFlashMode',         async () => { await cmdSelectFlashMode();         provider.refresh(); });
    reg('esp.selectFlashFreq',         async () => { await cmdSelectFlashFreq();         provider.refresh(); });
    reg('esp.selectFlashSize',         async () => { await cmdSelectFlashSize();         provider.refresh(); });
    reg('esp.toggleCompressedUpload',  async () => { await cmdToggleCompressedUpload();  provider.refresh(); });
    reg('esp.selectBeforeFlashing',    async () => { await cmdSelectBeforeFlashing();    provider.refresh(); });
    reg('esp.selectAfterFlashing',     async () => { await cmdSelectAfterFlashing();     provider.refresh(); });
    reg('esp.refreshViews', () => {
        setToolsVerified(false);
        setPythonCmdCache(null);
        const idfPath  = getValidIdfPath();
        if (idfPath) ensureVersionTxt(idfPath);
        provider.refresh();
        IdfRunner.checkEnvironment(true).catch(e => log(`checkEnvironment: ${e}`));
        IdfRunner.checkAndInstallTools(false).catch(e => log(`checkAndInstallTools: ${e}`));
    });
    reg('esp.showRtosSdkInfo', async () => {
        const rtosMsg = [
                '📁 ESP8266_RTOS_SDK/',
                '├── components/    ← required',
                '├── tools/         ← required',
                '├── CMakeLists.txt  ← required',
                '├── Kconfig         ← required',
                '└── requirements.txt ← required',
                '',
                'Download:',
                '  github.com/espressif/ESP8266_RTOS_SDK',
            ].join('\n');
        const rtosBtn = await vscode.window.showInformationMessage(
            'Expected RTOS SDK folder structure',
            { modal: true, detail: rtosMsg },
            'Copy to Clipboard', 'OK'
        );
        if (rtosBtn === 'Copy to Clipboard') vscode.env.clipboard.writeText(rtosMsg);
    });
    reg('esp.fixPython',               () => Python.cmdFixPython());
    reg('esp.fixSdk',                  async () => { await IdfRunner.cmdFixSdk(); });
    reg('esp.setPythonPath',           async () => { await Python.cmdSetPythonPath(); IdfRunner.checkEnvironment(true).catch(e => log(`checkEnvironment: ${e}`)); });
    reg('esp.collapseAll',             () => vscode.commands.executeCommand('workbench.actions.treeView.esp8266-idf.projectView.collapseAll'));
}

function deactivate() {
    clearBusy();
    setMonitorRunning(false);
    try {
        const tmpDir = os.tmpdir();
        const files = fs.readdirSync(tmpDir);
        for (const f of files) {
            if (/^esp_(bld|cmd|chain|pip|install|req|spiffs|fatfs|littlefs|ota|ota_switch|ota_erase|ota_read|flash_fs)_\d+\.tmp$/.test(f)) {
                try { fs.unlinkSync(path.join(tmpDir, f)); } catch {}
            }
        }
    } catch {}
    const terms = getTerms();
    for (const t of Object.values(terms)) { try { t.dispose(); } catch {} }
    setTerms({});
    const panel = getPartitionPanel();
    if (panel) { try { panel.dispose(); } catch {} setPartitionPanel(null); }
    const oc = getOutputChannel();
    if (oc) { try { oc.dispose(); } catch {} setOutputChannel(null); }
}

module.exports = { activate, deactivate };
